# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import img_embedding_pb2 as img__embedding__pb2


class ImgEmbeddingStub(object):
    """Service for obtaining the embedding of an image
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetImgEmbedding = channel.unary_unary(
                '/ImgEmbedding/GetImgEmbedding',
                request_serializer=img__embedding__pb2.Image.SerializeToString,
                response_deserializer=img__embedding__pb2.Float1DArray.FromString,
                )


class ImgEmbeddingServicer(object):
    """Service for obtaining the embedding of an image
    """

    def GetImgEmbedding(self, request, context):
        """Receives an image and returns its embedding from a VGG16
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImgEmbeddingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetImgEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImgEmbedding,
                    request_deserializer=img__embedding__pb2.Image.FromString,
                    response_serializer=img__embedding__pb2.Float1DArray.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImgEmbedding', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImgEmbedding(object):
    """Service for obtaining the embedding of an image
    """

    @staticmethod
    def GetImgEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ImgEmbedding/GetImgEmbedding',
            img__embedding__pb2.Image.SerializeToString,
            img__embedding__pb2.Float1DArray.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
